Game engine
hatchways/team-fettuccini pull request #21
Opened 2020-04-02 20:07 UTC by Flaagrah

Created basic framework for the game and created unit tests for Game and Board. All unit tests currently pass.

2020-04-03 14:46 UTC, pavel6767 approved these changes
this is amazing!
I ran tests locally and not sure if this is an issue, but seeing a statement printed twice whenever a team wins
i.e. Red Won
Red Won

2020-04-03 21:32 UTC, aeciorc requested changes
Other things to do merging this PR:
- Move the stuff from app.js to another script that we can use for testing
- Favour const over let and let over var

2020-04-03 21:32 UTC, aeciorc commented on server/engine/Board.js
> +		for (i = 0;i<25;i++)
```suggestion
		this.wordList = new Array(25);
		const dictSize = Dictionary.length;
		const wordMap = {};
		let red = 9;
		let blue = 8;
		let civilian = 7;
		let assassin = 1;
		for (let i = 0;i<25;i++)

```

2020-04-03 21:32 UTC, aeciorc commented on server/engine/Board.js
> +			}
The way you assign the words is pretty clever 👍

2020-04-03 21:32 UTC, aeciorc commented on server/engine/GameWord.js
> +const word_state = require("./WordStates.js");
use camelCase

2020-04-03 21:32 UTC, aeciorc commented on server/engine/GameWord.js
> +	}
Here as well

2020-04-03 21:32 UTC, aeciorc commented on server/engine/GameWord.js
> +}
```suggestion
		if (this.chosen) {
			return false;
		}
		this.chosen = true;
		return true;
	}
}

```

2020-04-03 21:32 UTC, aeciorc commented on server/engine/WordStates.js
> +var word_state = {
camelCase

2020-04-06 16:36 UTC, aeciorc approved these changes

2020-04-07 22:19 UTC, merged